// export { default as component } from './Folder/File'
export { default as TopNav } from './TopNav/TopNav.js'
export { default as Header } from './Home/Header.js'
export { default as Main } from './Home/Main.jsx'
export { default as Feature } from './Home/Feature.jsx'
export { default as Footer } from './Home/Footer.jsx'
export { default as FlashNews } from './News/FlashNews.js'
export { default as Blog } from './Details/Blog.js'

export { default as CardGraph } from './CardGraph/CardGraph.js'
export { default as CardDetails } from './CardData/CardDetails.js'
export { default as PopupData } from './Elements/PopupData.js'