# Generated by Django 4.2 on 2024-02-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInsertionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_data_been_inserted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_level', models.TextField()),
                ('vegetarian_friendly', models.BooleanField(default=False)),
                ('vegan_options', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('avg_rating', models.TextField()),
            ],
        ),
    ]
