# Generated by Django 4.2 on 2024-02-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_datainsertionstatus_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='avg_rating',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=10),
        ),
        migrations.AlterField(
            model_name='preference',
            name='price_level',
            field=models.CharField(choices=[('€', '€'), ('€€-€€€', '€€-€€€'), ('€€€€', '€€€€')], max_length=10),
        ),
    ]
