# Generated by Django 4.2 on 2024-02-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_alter_preference_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='region',
            field=models.TextField(default=''),
        ),
    ]
